export const countries = [
    { countryCode: "+93", countryName: "Afghanistan" },
    { countryCode: "+355", countryName: "Albania" },
    { countryCode: "+213", countryName: "Algeria" },
    { countryCode: "+376", countryName: "Andorra" },
    { countryCode: "+244", countryName: "Angola" },
    { countryCode: "+1-268", countryName: "Antigua and Barbuda" },
    { countryCode: "+54", countryName: "Argentina" },
    { countryCode: "+374", countryName: "Armenia" },
    { countryCode: "+61", countryName: "Australia" },
    { countryCode: "+43", countryName: "Austria" },
    { countryCode: "+994", countryName: "Azerbaijan" },
    { countryCode: "+1-242", countryName: "Bahamas" },
    { countryCode: "+973", countryName: "Bahrain" },
    { countryCode: "+880", countryName: "Bangladesh" },
    { countryCode: "+1-246", countryName: "Barbados" },
    { countryCode: "+375", countryName: "Belarus" },
    { countryCode: "+32", countryName: "Belgium" },
    { countryCode: "+501", countryName: "Belize" },
    { countryCode: "+229", countryName: "Benin" },
    { countryCode: "+975", countryName: "Bhutan" },
    { countryCode: "+591", countryName: "Bolivia" },
    { countryCode: "+387", countryName: "Bosnia and Herzegovina" },
    { countryCode: "+267", countryName: "Botswana" },
    { countryCode: "+55", countryName: "Brazil" },
    { countryCode: "+673", countryName: "Brunei Darussalam" },
    { countryCode: "+359", countryName: "Bulgaria" },
    { countryCode: "+226", countryName: "Burkina Faso" },
    { countryCode: "+257", countryName: "Burundi" },
    { countryCode: "+855", countryName: "Cambodia" },
    { countryCode: "+237", countryName: "Cameroon" },
    { countryCode: "+1", countryName: "Canada" },
    { countryCode: "+238", countryName: "Cape Verde" },
    { countryCode: "+236", countryName: "Central African Republic" },
    { countryCode: "+235", countryName: "Chad" },
    { countryCode: "+56", countryName: "Chile" },
    { countryCode: "+86", countryName: "China" },
    { countryCode: "+57", countryName: "Colombia" },
    { countryCode: "+269", countryName: "Comoros" },
    { countryCode: "+506", countryName: "Costa Rica" },
    { countryCode: "+225", countryName: "Cote d'Ivoire" },
    { countryCode: "+385", countryName: "Croatia" },
    { countryCode: "+53", countryName: "Cuba" },
    { countryCode: "+357", countryName: "Cyprus" },
    { countryCode: "+420", countryName: "Czech Republic" },
    { countryCode: "+243", countryName: "Democratic Republic of the Congo" },
    { countryCode: "+45", countryName: "Denmark" },
    { countryCode: "+253", countryName: "Djibouti" },
    { countryCode: "+1-767", countryName: "Dominica" },
    { countryCode: "+1-809", countryName: "Dominican Republic" },
    { countryCode: "+670", countryName: "East Timor" },
    { countryCode: "+593", countryName: "Ecuador" },
    { countryCode: "+20", countryName: "Egypt" },
    { countryCode: "+503", countryName: "El Salvador" },
    { countryCode: "+240", countryName: "Equatorial Guinea" },
    { countryCode: "+291", countryName: "Eritrea" },
    { countryCode: "+372", countryName: "Estonia" },
    { countryCode: "+251", countryName: "Ethiopia" },
    { countryCode: "+679", countryName: "Fiji" },
    { countryCode: "+358", countryName: "Finland" },
    { countryCode: "+33", countryName: "France" },
    { countryCode: "+241", countryName: "Gabon" },
    { countryCode: "+220", countryName: "Gambia" },
    { countryCode: "+995", countryName: "Georgia" },
    { countryCode: "+49", countryName: "Germany" },
    { countryCode: "+233", countryName: "Ghana" },
    { countryCode: "+30", countryName: "Greece" },
    { countryCode: "+1-473", countryName: "Grenada" },
    { countryCode: "+502", countryName: "Guatemala" },
    { countryCode: "+224", countryName: "Guinea" },
    { countryCode: "+245", countryName: "Guinea-Bissau" },
    { countryCode: "+592", countryName: "Guyana" },
    { countryCode: "+509", countryName: "Haiti" },
    { countryCode: "+504", countryName: "Honduras" },
    { countryCode: "+852", countryName: "Hong Kong" },
    { countryCode: "+36", countryName: "Hungary" },
    { countryCode: "+354", countryName: "Iceland" },
    { countryCode: "+91", countryName: "India" },
    { countryCode: "+62", countryName: "Indonesia" },
    { countryCode: "+98", countryName: "Iran" },
    { countryCode: "+964", countryName: "Iraq" },
    { countryCode: "+353", countryName: "Ireland" },
    { countryCode: "+972", countryName: "Israel" },
    { countryCode: "+39", countryName: "Italy" },
    { countryCode: "+1-876", countryName: "Jamaica" },
    { countryCode: "+81", countryName: "Japan" },
    { countryCode: "+962", countryName: "Jordan" },
    { countryCode: "+7", countryName: "Kazakhstan" },
    { countryCode: "+254", countryName: "Kenya" },
    { countryCode: "+686", countryName: "Kiribati" },
    { countryCode: "+850", countryName: "North Korea" },
    { countryCode: "+82", countryName: "South Korea" },
    { countryCode: "+965", countryName: "Kuwait" },
    { countryCode: "+996", countryName: "Kyrgyzstan" },
    { countryCode: "+856", countryName: "Laos" },
    { countryCode: "+371", countryName: "Latvia" },
    { countryCode: "+961", countryName: "Lebanon" },
  ];