export const otherLinks = [
    { title: "About Us", link: "https://www.cleartrip.com/" },
    { title: "Careers", link: "https://careers.cleartrip.com/#!/" },
    { title: "FAQs", link: "https://www.cleartrip.com/faq/" },
    { title: "Support", link: "https://www.cleartrip.com/support" },
    { title: "Collections", link: "https://www.cleartrip.com/collections/" },
    { title: "Cleartrip for Business", link: "https://business.cleartrip.com/" },
    { title: "Gift Cards", link: "https://www.cleartrip.com/lp/giftcards/" },
  ];
  
  export const footerFlightHotelLinks = [
    {
      title: "Popular Domestic Flight Routes",
      routeLocation: [
        { name: "Delhi Goa flights", link: "" },
        { name: "Mumbai Delhi flights", link: "" },
        { name: "Delhi Kolkata flights", link: "" },
        { name: "Pune Delhi flights", link: "" },
        { name: "Bangalore Delhi flights", link: "" },
        { name: "Mumbai Bangalore flights", link: "" },
        { name: "Chennai Delhi flights", link: "" },
        { name: "Kolkata Delhi flights", link: "" },
        { name: "Delhi Mumbai flights", link: "" },
        { name: "Delhi Bangalore flights", link: "" },
        { name: "Mumbai Goa flights", link: "" },
      ],
    },
    {
      title: "Popular International Flight Routes",
      routeLocation: [
        { name: "Delhi Singapore flights", link: "" },
        { name: "Delhi Bangkok flights", link: "" },
        { name: "Mumbai Dubai flights", link: "" },
        { name: "Delhi Dubai flights", link: "" },
        { name: "Delhi to London flights", link: "" },
        { name: "Delhi to Toronto flights", link: "" },
        { name: "Delhi to New york flights", link: "" },
        { name: "Bangalore to Singapore flights", link: "" },
        { name: "Delhi to Paris flights", link: "" },
        { name: "Mumbai to Paris flights", link: "" },
        { name: "Delhi to Hong Kong flights", link: "" },
      ],
    },
    {
      title: "Popular hotels",
      routeLocation: [
        { name: "Goa hotels", link: "" },
        { name: "Mumbai hotels", link: "" },
        { name: "Bangalore hotels", link: "" },
        { name: "Chennai hotels", link: "" },
        { name: "Nainital hotels", link: "" },
        { name: "Jaipur hotels", link: "" },
        { name: "Manali hotels", link: "" },
        { name: "Shimla hotels", link: "" },
        { name: "Pune hotels", link: "" },
        { name: "Hyderabad hotels", link: "" },
        { name: "Mahabaleshwar hotels", link: "" },
        { name: "Ooty hotels", link: "" },
        { name: "Kolkata hotels", link: "" },
        { name: "Matheran hotels", link: "" },
        { name: "Shirdi hotels", link: "" },
        { name: "Agra hotels", link: "" },
        { name: "Mysore hotels", link: "" },
        { name: "Munnar hotels", link: "" },
        { name: "Delhi hotels", link: "" },
        { name: "Kodaikanal hotels", link: "" },
      ],
    },
    {
      title: "Popular hotel chains",
      routeLocation: [
        { name: "Taj group", link: "" },
        { name: "Sarovar group of hotels", link: "" },
        { name: "V resorts", link: "" },
        { name: "Fortune hotels", link: "" },
        { name: "Carlson hotels", link: "" },
        { name: "Concept", link: "" },
        { name: "Royal orchid hotels", link: "" },
        { name: "Lemon tree hotels", link: "" },
        { name: "Ginger", link: "" },
        { name: "Club mahindra", link: "" },
        { name: "Clarks inn group of hotels", link: "" },
        { name: "Welcomheritage", link: "" },
        { name: "Accor group of hotels", link: "" },
        { name: "World choice hotels", link: "" },
        { name: "Genx/1589 group", link: "" },
        { name: "Lords hotels & resorts", link: "" },
        { name: "Keys", link: "" },
        { name: "Sterling resort", link: "" },
        { name: "Golden tulip hotels", link: "" },
        { name: "Trident/oberoi hotels", link: "" },
      ],
    },
    {
      title: "Other Links",
      routeLocation: [
        { name: "Cheap air tickets", link: "" },
        { name: "Flight tickets", link: "" },
        { name: "India Hotels", link: "" },
        { name: "Cheap Domestic Air Tickets", link: "" },
        { name: "Domestic Flights", link: "" },
        { name: "Domestic Airlines in India", link: "" },
        { name: "International Air Tickets", link: "" },
        { name: "International Flights", link: "" },
        { name: "International Airlines", link: "" },
        { name: "Holiday Packages", link: "" },
      ],
    },
    {
      title: "Useful Links",
      routeLocation: [{ name: "Myntra", link: "" }],
    },
  ];